name: steinstadion-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=1.26
  - scipy>=1.12.1
  - pandas=2.2
  - matplotlib=3.9
  - seaborn=0.13
  - scikit-learn=1.5
  - jupyterlab=4.2
  - notebook=7.2
  - ipywidgets=7.8
  - h5py=3.11
  - statsmodels=0.14
  - networkx=3.3
  - tqdm=4.66
  - sympy=1.13.1
  - xgboost=3.0.2
  - pytorch=2.6.0
  - tensorflow=2.18.0
  - tensorboard=2.18.0
  - jax=0.6.2
  - jaxlib=0.6.2
  - flax=0.10.7
  - optax=0.2.4
  - chex=0.1.88
  - pip
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - autograd==1.7.0
      - causaldag==0.1a163
      - conditional-independence==0.1a6
      - dm-tree==0.1.9
      - einops==0.8.1
      - etils==1.11.0
      - opt-einsum==3.4.0
      - pgmpy==1.0.0
      - pyro-ppl==1.9.1
      - umap==0.1.1
      - wandb==0.19.5


