name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - alabaster=1.0.0
  - applaunchservices=0.3.0
  - appnope=0.1.4
  - archspec=0.2.5
  - arrow=1.3.0
  - astroid=3.3.11
  - asttokens=3.0.0
  - async-timeout=5.0.1
  - asyncssh=2.21.0
  - atomicwrites=1.4.1
  - attrs=25.3.0
  - autopep8=2.0.4
  - babel=2.17.0
  - backports=1.0
  - backports.tarfile=1.2.0
  - bcrypt=4.3.0
  - beautifulsoup4=4.13.4
  - binaryornot=0.4.4
  - black=25.1.0
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - boltons=25.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - certifi=2025.8.3
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.2
  - click=8.2.2
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.3
  - conda=25.5.1
  - conda-libmamba-solver=25.4.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - cookiecutter=2.6.0
  - cpp-expected=1.1.0
  - cryptography=45.0.5
  - cyrus-sasl=2.1.27
  - debugpy=1.8.15
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - diff-match-patch=20241021
  - dill=0.4.0
  - distro=1.9.0
  - docstring-to-markdown=0.17
  - docutils=0.21.2
  - double-conversion=3.1.5
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - flake8=7.1.2
  - fmt=11.1.4
  - frozendict=2.4.6
  - frozenlist=1.7.0
  - fzf=0.65.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.10
  - imagesize=1.4.1
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - inflection=0.5.1
  - intervaltree=3.1.0
  - ipykernel=6.30.1
  - ipython=8.37.0
  - isort=6.0.1
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.1
  - jaraco.functools=4.2.1
  - jedi=0.19.2
  - jellyfish=1.1.3
  - jinja2=3.1.6
  - jpeg=9e
  - jsoncpp=1.9.4
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.4.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_pygments=0.3.0
  - keyring=25.6.0
  - krb5=1.20.1
  - libabseil=20240116.2
  - libarchive=3.7.7
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libclang13=14.0.6
  - libcurl=8.14.1
  - libcxx=20.1.8
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.4.6
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libgrpc=1.62.2
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libkrb5=1.21.3
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmamba=2.1.0
  - libmambapy=2.1.0
  - libnghttp2=1.57.0
  - libntlm=1.8
  - libopenblas=0.3.29
  - libpng=1.6.43
  - libpq=17.4
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsolv=0.7.30
  - libspatialindex=2.1.0
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libxml2=2.13.8
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - mdurl=0.1.2
  - menuinst=2.3.0
  - mistune=3.1.3
  - ml_dtypes=0.5.1
  - more-itertools=10.7.0
  - multidict=6.6.3
  - mypy_extensions=1.1.0
  - mysql=8.4.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.3
  - numpydoc=1.9.0
  - openldap=2.6.5
  - openssl=3.5.1
  - opt_einsum=3.3.0
  - packaging=25.0
  - pandoc=3.7.0.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pathspec=0.12.1
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1.1
  - platformdirs=4.3.8
  - pluggy=1.6.0
  - ply=3.11
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=4
  - pycodestyle=2.12.1
  - pyconify=0.2.1
  - pycosat=0.6.6
  - pycparser=2.22
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygithub=2.7.0
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pylint=3.3.7
  - pylint-venv=3.0.4
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyobjc-core=11.1
  - pyobjc-framework-cocoa=11.1
  - pyobjc-framework-coreservices=11.1
  - pyobjc-framework-fsevents=11.1
  - pyopenssl=25.1.0
  - pyqt=5.15.4
  - pyqtwebengine=5.15.4
  - pysocks=1.7.1
  - python=3.10.6
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-gssapi=1.8.2
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.12.2
  - python-lsp-server-base=1.12.2
  - python-slugify=8.0.4
  - python.app=1.4
  - python_abi=3.10
  - pytoolconfig=1.2.5
  - pytz=2025.2
  - pyuca=1.2
  - pyxdg=0.28
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qdarkstyle=3.2.3
  - qstylizer=0.2.4
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.4.0
  - qtconsole=5.6.1
  - qtconsole-base=5.6.1
  - qtpy=2.4.3
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.36.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.4
  - rich=14.1.0
  - rope=1.14.0
  - rpds-py=0.26.0
  - rtree=1.4.0
  - ruamel.yaml=0.18.14
  - ruamel.yaml.clib=0.2.8
  - scipy=1.15.3
  - setuptools=80.9.0
  - simdjson=3.12.3
  - sip=6.12.0
  - six=1.17.0
  - snappy=1.2.1
  - snowballstemmer=3.0.1
  - sortedcontainers=2.4.0
  - soupsieve=2.7
  - spdlog=1.15.3
  - sphinx=8.1.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - spyder=6.0.7
  - spyder-base=6.0.7
  - spyder-kernels=3.0.5
  - sqlite=3.46.0
  - stack_data=0.6.3
  - superqt=0.7.5
  - text-unidecode=1.3
  - textdistance=4.6.3
  - three-merge=0.1.1
  - tinycss2=1.4.0
  - tk=8.6.14
  - toml=0.10.2
  - tomli=2.2.1
  - tomlkit=0.13.3
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - truststore=0.10.1
  - types-python-dateutil=2.9.0.20250708
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - ujson=5.10.0
  - urllib3=2.5.0
  - watchdog=6.0.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - whatthepatch=1.0.7
  - wheel=0.45.1
  - wrapt=1.17.2
  - wurlitzer=3.1.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yapf=0.43.0
  - yarl=1.20.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - causaldag==0.1a163
      - cdt==0.5.23
      - chex==0.1.90
      - conditional-independence==0.1a6
      - contourpy==1.3.2
      - cycler==0.12.1
      - dataclasses==0.6
      - dm-tree==0.1.9
      - docstring-parser==0.17.0
      - einops==0.8.1
      - equinox==0.13.0
      - etils==1.13.0
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fonttools==4.59.0
      - fsspec==2025.7.0
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-pasta==0.2.0
      - gputil==1.4.0
      - graphical-model-learning==0.1a8
      - graphical-models==0.1a21
      - grpcio==1.74.0
      - h5py==3.14.0
      - igraph==0.11.9
      - immutabledict==4.2.1
      - ipdb==0.13.13
      - jax==0.6.2
      - jaxlib==0.6.2
      - jaxopt==0.8.5
      - jaxtyping==0.3.2
      - joblib==1.5.1
      - keras==3.11.1
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - lineax==0.0.8
      - markdown==3.8.2
      - matplotlib==3.10.5
      - mpmath==1.3.0
      - namex==0.1.0
      - networkx==3.4.2
      - numexpr==2.11.0
      - numpy==1.26.4
      - optax==0.2.5
      - optree==0.17.0
      - ott==0.1.15
      - ott-jax==0.5.1
      - pandas==2.3.1
      - patsy==1.0.1
      - pgmpy==1.0.0
      - pillow==11.3.0
      - polars==0.20.18
      - progressbar2==4.5.0
      - promise==2.3
      - protobuf==4.21.12
      - pyarrow==21.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygam==0.10.1
      - pyparsing==3.2.3
      - pyqt5-sip==12.9.0
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - python-utils==3.9.1
      - rpy2==3.6.2
      - rpy2-rinterface==3.6.2
      - rpy2-robjects==3.6.1
      - scikit-learn==1.7.1
      - seaborn==0.13.2
      - sentry-sdk==2.34.1
      - sergio==1.2
      - sergio-rs==0.2.0
      - simple-parsing==0.1.7
      - skrebate==0.62
      - smmap==5.0.2
      - statsmodels==0.14.5
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-datasets==4.9.9
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.17.2
      - termcolor==3.1.0
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - toolz==1.0.0
      - torch==2.7.1
      - typing==3.7.4.3
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - tzlocal==5.3.1
      - umap==0.1.1
      - wadler-lindig==0.1.7
      - wandb==0.21.0
      - werkzeug==3.1.3
      - xgboost==3.0.3
